### ISSUE TITLE
TypeError: Cannot convert undefined or null to object (installHook.js)

### ISSUE THREAD

**Issue by iki** [React-Sight/React-Sight#143]
```
installHook.js:1 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Module.12 (installHook.js:1)
    at n (installHook.js:1)
    at installHook.js:1
    at installHook.js:1
```
on any site in Opera 64.0.3409.0

**Comment by ssr714** [comment]
I face the same issue in Latest chrome Version 76.0.3809.100 (Official Build) (64-bit).

**Comment by jscriptcoder** [comment]
I just noticed this line, https://github.com/React-Sight/React-Sight/blob/master/chrome-ext/backend/installHook.js#L16

I think it should be instead:

```javascript
const reactInstances = window.__REACT_DEVTOOLS_GLOBAL_HOOK__.renderers || null;
```
Notice it's ```renderers```, instead of ```_renderers```

**Comment by ortonomy** [comment]
same issue. uninstalling until this is fixed. Watching issue.

**Comment by prma85** [comment]
same here :(

**Comment by OutThisLife** [comment]
+1

**Comment by davidcsally** [comment]
Think I fixed this here: https://github.com/React-Sight/React-Sight/pull/202, will publish an update soon

**Comment by davidcsally** [comment]
Closing, this should be fixed now. If it pops back up feel free to re-open!
