### ISSUE TITLE
Cannot find React  Triggering a setState() usually fixes this

### ISSUE THREAD

**Issue by BarishSarac** [React-Sight/React-Sight#145]
I am getting this error when I run the React-Sight..
`Cannot find React  Triggering a setState() usually fixes this`

**Comment by picolloo** [comment]
I'm getting this error too.

**Comment by pikonha** [comment]
+1

**Comment by meligatt** [comment]
+1

**Comment by Boeblahoebla** [comment]
Same here...

**Comment by onlyrams** [comment]
+1

**Comment by hlmifzi** [comment]
same here

**Comment by sabrif31** [comment]
+1

**Comment by hoggworks** [comment]
+1

Triggering setState didn't work for me.

**Comment by ksundeen** [comment]
+1 Will be watching this thread. FYI - I also installed react-dom and react packages @16.6.0 to test, but received the same errors. I'll try previous versions too.

**Comment by MirrorHuang** [comment]
+1

**Comment by braxex** [comment]
+1

**Comment by larryrutledge** [comment]
+1 following as I have the same issue

**Comment by shantanutomar** [comment]
Facing same issue +1

**Comment by iceniveth** [comment]
Same issue with Chrome 79.0.3945.88

**Comment by leefsmp** [comment]
Works nada +1

**Comment by polyak-y** [comment]
+1

**Comment by matheusggds** [comment]
+1

**Comment by 0j-xie0** [comment]
This would be an awesome tool to have. Hope it gets fixed!

**Comment by davidcsally** [comment]
Duplicate of this issue --> https://github.com/React-Sight/React-Sight/issues/134 Tracking a fix PR over there.

**Comment by DimuthuRoshan** [comment]
I am getting the following error 
`Cannot find React Triggering a setState() usually fixes this`
with version 1.1.0

**Comment by Ex4l** [comment]
I'm getting this error message either.

```
Cannot find React. Triggering a setState() usually fixes this
```

**Comment by mohammed-kudos** [comment]
same problem

**Comment by philxavier** [comment]
same here guys =/

**Comment by nico-hernandez** [comment]
in the same boat

**Comment by kgloveyou** [comment]
same problem

**Comment by Wonder2210** [comment]
Same problem in this side
