### ISSUE TITLE
"Cannot read property getState of undefined"

### ISSUE THREAD

**Issue by prescottprue** [React-Sight/React-Sight#85]
First off: Thanks for the great package

Following basic setup instructions causes the following issue:

<img width="1273" alt="screen shot 2017-10-12 at 12 06 53 pm" src="https://user-images.githubusercontent.com/2992224/31514333-26484fe0-af46-11e7-9abe-b63a10182221.png">

It looks like it is assuming that all components are getting store? Not sure why the check for the property isn't catching it.

**Comment by tbranyen** [comment]
I had the same issue when trying to use this module on my app.

**Comment by davidcsally** [comment]
Thanks @prescottprue and @tbranyen! Could you let us know if you're using Redux, and what version of React / Redux you are using? Also, if you have any additional code to share to help us debug this, it would be greatly appreciated!

For the short term, we could try removing the call to the redux store by removing lines 95-102 in 'chrome-ext/backend/installHook.js'.

I updated the readme to include instructions on how to build and load a custom version of the extension.

**Comment by tbranyen** [comment]
```
    "redux": "3.6.0",
    "react": "15.6.1",
    "react-redux": "5.0.5",
```

**Comment by betoharres** [comment]
I'm getting this error too.
Here's my `yarn.lock`: https://pastebin.com/GGVsPNVQ

I hope this helps! Great library btw! 👍 

**EDIT**: I'm using create-react-app

**Comment by mike-es6** [comment]
Getting the same problem. Should the code also check that there actually *is* a state property and that it and that it has a getState method? Someone not using redux might use a *state* prop to mean something else, for instance.

**Comment by prescottprue** [comment]
@mike-es6 I think that is exactly what would fix it

**Comment by davidcsally** [comment]
Fixed it here https://github.com/React-Sight/React-Sight/pull/202

**Comment by davidcsally** [comment]
Going to close
