### ISSUE TITLE
Salesforce.com compatibility: "[NoErrorObjectAvailable] Script error."

### ISSUE THREAD

**Issue by ghuroo** [React-Sight/React-Sight#89]
When the **React-Sight** chrome extension is enabled, the **Salesforce Lightning Platform** encounters a generic error: "[NoErrorObjectAvailable] Script error.".

This does not happen when using the **Salesforce Classic Platform**.

![error](https://user-images.githubusercontent.com/4954762/31541084-7350c2b2-b005-11e7-9870-d7557e19df24.png)
![extensions](https://user-images.githubusercontent.com/4954762/31541091-776c86f6-b005-11e7-8f50-4f1c51b1d7b2.png)

**Note:** Using only the "**React Developer Tools**" extension does not give any conflict with Salesforce Lightning.

**Temporary solution:** Just disable the **React-Sight** extension.

**Comment by davidcsally** [comment]
We will investigate this. We are working on an update to provide better compatibility

**Comment by chriscorwin** [comment]
Seeing another error while using SLDS - an internal version that isn’t public yet, so I can’t help with “details”, but, yeah, this is an issue I am seeing also. :(

**Comment by saurabhhGitHub** [comment]
I am also facing "[NoErrorObjectAvailable] Script error." even no React-Sight chrome extension is enabled.

**Comment by anupkage** [comment]
I'm also getting this error. When I try to update the data dynamically
```
@track tasks = []; // it contains task records
handleChange(event) {
	let response = event.detail;
	let rec = this.tasks[response.index];    
	// checked null values
	rec[response.realApiName] = response.value; // Error on this Line  if we comment this part then it works
}
```

**Comment by peghenderson1** [comment]
I am also facing "[NoErrorObjectAvailable] Script error." even no React-Sight chrome extension is enabled.  It occured in my Sandbox after I performed a Match production and sandbox licenses without a sandbox refresh.

**Comment by sandeepsharmagrazitti** [comment]
Same issue with Grammarly for Chrome

**Comment by emmabindi** [comment]
I also encountered this same issue in Chrome only - working fine in Firefox. I do not have Grammarly in either

**Comment by lnunezSFDC** [comment]
I'm facing the same issue with salesforce surveys on chrome for IOS
