### ISSUE TITLE
feature request: zooming in and out in the component tree.

### ISSUE THREAD

**Issue by koenverburg** [React-Sight/React-Sight#92]
I'm working on a large scale app in React and this is an awesome tool!. Could you add the ability to zoom in and out?

**Comment by Grant05** [comment]
You can zoom by double clicking/zoom out shift + dbl click.

**Comment by palnes** [comment]
Should be documented, especially since the demo allows for pinch-to-zoom. :) I just uninstalled the entire extension because it seemed pretty useless without it.
