### ISSUE TITLE
Separate core vs extension

### ISSUE THREAD

**Issue by Raathigesh** [React-Sight/React-Sight#93]
Great work. Big fan of UI based dev tools.

When I looked at this project I was like "Oh! this would be an awesome thing to integrate into the tool I'm building" and then realized this is an extension. 

Would it make sense to separate the core visualization component into a separate package and push it to npm and the keep extension code in a separate package using tools like lerna or yarn workspaces so others can take advantage of the core components and integrate to other tools?

**Comment by Grant05** [comment]
We have an npm module that's currently published but out of date, we plan on updating it very soon. Thanks for the feedback
