### ISSUE TITLE
feature request: Support React-Native

### ISSUE THREAD

**Issue by timwangdev** [React-Sight/React-Sight#94]
React Devtool and Redux Devtool, both have support with React-Native, and can be debugged from Chrome. Maybe there is some way to adapter this tool for RN apps.

**Comment by davidcsally** [comment]
This is something we would love to look into after we improve reliability across React / DOM

**Comment by davidcsally** [comment]
I'm never gonna do this, so closing. I welcome any PRs that want to tackle this!
