### ISSUE TITLE
Cannot find imported React library - no console error

### ISSUE THREAD

**Issue by ido-ofir** [React-Sight/React-Sight#95]
![image](https://user-images.githubusercontent.com/6238323/31584061-4e8d2c62-b1af-11e7-95bb-606e15d950c7.png)

there is no error in the console.

**Comment by yifeng-ruan** [comment]
I met the same issue.

**Comment by finnigantime** [comment]
I get this too, but I do see a console error for code in the React-Sight plugin: 
<img width="557" alt="screen shot 2017-11-03 at 10 02 35 am" src="https://user-images.githubusercontent.com/1305608/32386369-30637f6a-c07e-11e7-895a-00c3110776c6.png">

This is on a fresh install of React-Sight from the Chrome store. We're on React v15.5.4.

**Comment by 6ewis** [comment]
+1

**Comment by davidcsally** [comment]
I know this is kinda late, but if I'm understanding it correctly, there's no console error when React Sight can't find React.  I've added a console.log to notify users if React isn't found 

installHook.js
      console.log('[React Sight] React not found');

**Comment by davidcsally** [comment]
Closing this
