### ISSUE TITLE
React-Sight overwrites window.store

### ISSUE THREAD

**Issue by nschomberg** [React-Sight/React-Sight#96]
React-Sight overwrites `window.store`, interfering with other libraries that also rely on that variable being there.

Could React-Sight maybe use a less common variable name for storing its data? Or perhaps use a namespace?

**Comment by davidcsally** [comment]
@nschomberg this was a noob mistake on our end, pushing an update soon

**Comment by davidcsally** [comment]
variables have been renamed

**Comment by nschomberg** [comment]
Awesome, thanks for the quick turnaround.
