### ISSUE TITLE
`window.store` is manipulated after `react-sight` chrome extension is installed

### ISSUE THREAD

**Issue by mocheng** [React-Sight/React-Sight#98]
In my project, `window.store` is a reference to Redux store instance. After installing react-sight, the `window.store` is manipulated to state object after page load. 

It takes me half an hour to identify the root cause after I uninstalling react-sight chrome extension. Perhaps better to have a clue in README.md so that user avoids to use `window.store`.

**Comment by davidcsally** [comment]
We are refactoring the code and renaming all variables so that we don't run into anymore conflicts like this. Expect an update soon!

**Comment by davidcsally** [comment]
variables have been renamed
