### ISSUE TITLE
Converting circular structure of JSON

### ISSUE THREAD

**Issue by psenderos** [React-Sight/React-Sight#99]
Hi,
I've tried to use it on my app, but at the start it show in console this error

> installHook.js:59 Uncaught TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at getData (installHook.js:59)
    at window.addEventListener (installHook.js:189)

**Comment by qborreda** [comment]
Same here .. but this project looks very promising!

**Comment by davidcsally** [comment]
Im still looking into this, not 100% how to fix it yet. I need to figure out a clean way to strip out circular references.

**Comment by jmansor** [comment]
I'm also experiencing this bug, cannot get it to work. Excited to test this tool in my project.

**Comment by davidcsally** [comment]
Finally fixed this - https://github.com/React-Sight/React-Sight/pull/202
